language: python
arch:
  - amd64
  - ppc64le
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install: "python setup.py develop"

# command to run tests
script: "python setup.py test"
